### ISSUE TITLE
OMNA-Registration of LWM2M Meta Object

### ISSUE THREAD

**Issue by github-oma** [OpenMobileAlliance/OMA_LwM2M_for_Developers#406]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2018-09-05 18:31:10 UTC</td></tr><tr><td>Submitter's name</td><td>Bill Silverajan</td></tr><tr><td>Defined By</td><td>Private company</td></tr><tr><td>Organization</td><td>Tampere University of Technology</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>LWM2M Meta Object</td></tr><tr><td>Object Description</td><td>A meta object to provide one or more locations for XML files defining vendor-specific objects.</td></tr><tr><td>Download Object</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=530259bf-5d3d-4aa0-9c67-20bfd30990ef_Object.xml">Link to object (zip)</a></td></tr><tr><td></td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/OMNA/530259bf-5d3d-4aa0-9c67-20bfd30990ef_Object.xml">Link to object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=530259bf-5d3d-4aa0-9c67-20bfd30990ef_Object.xml">Load Editor with object</a></td></tr>

**Comment by dnav** [comment]
One question: why make resource MD5 mandatory ?  
If the xml is hosted on a separate server, any "cosmetic" modification to the file (updating license or a description) would require to update all the LwM2M Clients having a reference to this xml.

Also, you should specify the format of the string for the MD5 (decimal, hex value, base64) or maybe make it an Opaque with a 128-bit range.

My 2 cts,

**Comment by bsilverajan** [comment]
For our own usage scenario, the checksum provides a simple way to detect tampering, and ensuring that if multiple instances of the URL field are present, they refer to the same definition. It is an informative resource, and the server can choose not to perform any operations if there is a mismatch. Having said that, if the object seems useful for adoption by others if the MD5 resource s made optional, I'm ok with that.

The format is a string, representing the hex value. What would be the best/recommended way to supply these changes?

**Comment by dnav** [comment]
> The format is a string, representing the hex value.

Speaking from experience, you should be precise on the format. Lowercase or uppercase letters ? Is there a prefix ? There are [multiple possibilities](https://en.wikipedia.org/wiki/Hexadecimal#Written_representation).

**Comment by seanmcilroy29** [comment]
The current registration has been validated against the ```Verification of OMNA Registry``` tool and it has identified gaps between the following;         
```<RangeEnumeration > </RangeEnumeration>```
```<Units> </Units>```
I've cleaned up the file and attached here. 
[LWM2M Meta Object.zip](https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/files/2370758/LWM2M.Meta.Object.zip) This file will be applied for this registration

**Comment by bsilverajan** [comment]
@dnav Thank you for the useful advice. I shall take the chance to revise the object model. Considering the feedback, I feel it would be useful to replace the MD5 resource field into 2 new optional resources: ChecksumType and ChecksumValue.

ChecksumType is an uppercase string describing the hash function used on the XML file(such as "MD5", "SHA-1", "SHA-256", etc).
ChecksumValue is an uppercase string containing only the hex value without a prefix (ie. no "0x" prepended").

Would you have an opinion on this amendment?

@seanmcilroy29 Thank you for the file. As there are likely to be some modifications based on David's feedback, could you please provide some guidance about how to apply any changes to the XML file from this point on?

**Comment by seanmcilroy29** [comment]
@bsilverajan - The best option is to;
- [ ] Finalise all the modifications/updates to the XML file
- [ ]  Submit the updated file to a new registration to offer individuals the option to view the modified object via the Editor tool and to submit comments. If you'd like me to to review the file prior to submission you can do this via smcilroy@omaorg.org
- [ ]  Close this issue (Link to new registration)

**Comment by jpradocueva** [comment]
@bsilverajan in addition to Sean's comment. I suggest that you import the file provided by Sean into the [Editor tool](
http://devtoolkit.openmobilealliance.org/OEditor/Legal?back=default.aspx). If you need assistance with the "import" function could have a look in these simple [guidelines](
https://wiki.openmobilealliance.org/display/TOOL/eLwM2M+Editor)
